"""add category to courses

Revision ID: 6455d9e06e81
Revises: 265ea9cf5ad5
Create Date: 2026-03-07 11:59:48.722261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6455d9e06e81'
down_revision: Union[str, Sequence[str], None] = '265ea9cf5ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'category')
    # ### end Alembic commands ###
